### ISSUE TITLE
No Camera Detected Consistently

### ISSUE THREAD

**Issue by SteveMacenski** [code-iai/pico_flexx_driver#11] opened 2017-06-20 07:38 UTC
Frequently one of my cameras isn't recognized requiring me to plug and unplug it. That's fine for a toy, but for a deployed product, I cannot design a picoflexx into something if it doesn't come up every time without me digging through the insides of the product. 

Is there a fix being worked on to solve this?

**Comment by GarrettPlace** [comment] 2017-06-20 12:00
Hi Steven - I am sorry to hear about the challenges.  I work for both pmd and ifm and would like to learn more about the issue you are experiencing.  You can reach me at garrett.place@ifm.com.

**Comment by SteveMacenski** [comment] 2017-06-20 22:45
I will email thanks!

**Comment by amaldo** [comment] 2017-06-30 14:07
I can't reproduce it in our lab. The camera always gets correctly detected. Could this be a hardware issue on your specific sensor? If this is not a pico_flexx_driver issue, please let us know to close this issue.

**Closed as completed** 2017-07-03 09:31 UTC
