### ISSUE TITLE
[Solved] libusb error on trying to build

### ISSUE THREAD

**Issue by nkhedekar** [code-iai/pico_flexx_driver#23] opened 2019-09-12 01:10 UTC
The following error is caused on trying to run catkin build for the ros package while installing on a Jetson TX2. It seems to be caused due an old version of libusb that is installed by ROS Kinetic. 

```bash
Errors     << pico_flexx_driver:make /home/nvidia/temp_ws/logs/pico_flexx_driver/build.make.002.log                                                                                                                                  
/home/nvidia/temp_ws/src/pico_flexx_driver/royale/libroyale-3.21.1.70-LINUX-arm-64Bit/bin/libroyale.so: undefined reference to `libusb_get_device_speed'
/home/nvidia/temp_ws/src/pico_flexx_driver/royale/libroyale-3.21.1.70-LINUX-arm-64Bit/bin/libroyale.so: undefined reference to `libusb_handle_events_completed'
/home/nvidia/temp_ws/src/pico_flexx_driver/royale/libroyale-3.21.1.70-LINUX-arm-64Bit/bin/libroyale.so: undefined reference to `libusb_set_auto_detach_kernel_driver'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/nvidia/temp_ws/devel/.private/pico_flexx_driver/lib/pico_flexx_driver/pico_flexx_driver] Error 1
make[1]: *** [CMakeFiles/pico_flexx_driver.dir/all] Error 2
make: *** [all] Error 2
cd /home/nvidia/temp_ws/build/pico_flexx_driver; catkin build --get-env pico_flexx_driver | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```

This can be fixed by moving the `libusb.so` referenced by running the `ldd` command on `libroyale.so`  in the downloaded driver like this: 
```bash
sudo mv /opt/ros/kinetic/lib/libusb-1.0.so.0 ~/Desktop/
```
Running the `ldd` command again will return something like: 
```bash
libusb-1.0.so.0 => /lib/aarch64-linux-gnu/libusb-1.0.so.0 (0x0000007f7ef76000)
```

**Comment by mintar** [comment] 2019-09-12 07:45
I'm glad that you could solve it. And thanks for reporting the issue, it will be very useful in case other users have the same problem.

Do you know which package the file is from? I couldn't find it on my system. You can use the following command to find out:

```bash
dpkg -S /opt/ros/kinetic/lib/libusb-1.0.so.0
```

I believe the best way to deal with this situation is to remove that package. Closing because the issue is solved.

**Closed as completed by mintar** 2019-09-12 07:45 UTC
